# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
defaults: &defaults
  working_directory: ~/repo
  docker: 
    - image: cimg/node:6
jobs:
  test:
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: npm test

      - store_artifacts: 
          path: ~/repo/coverage
          destination: coverage

      - persist_to_workspace:
          root: ~/repo
          paths: .

      
  # Is it time to publish? This step sure thinks so...
  deploy:
    <<: *defaults
    steps: 
      - attach_workspace:
          at: ~/repo
      - run: 
          name: Authenticate with repo
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package to npm
          command: npm publish
      - setup_remote_docker:
          docker_layer_caching: true

      - run: 
          name: Publish to dockerhub
          command: |
            docker build -t igwgames/cruddie-mock:$CIRCLE_TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push igwgames/cruddie-mock:$CIRCLE_TAG


workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
